package constant

// CommonProperty 定义公共常量
type CommonProperty struct{}

// TRANSACTION_COMMIT_STAGE 事务提交阶段
const TRANSACTION_COMMIT_STAGE = "SHIELD_TXC_COMMIT_"

// TRANSACTION_ROLLBACK_STAGE 事务回滚阶段
const TRANSACTION_ROLLBACK_STAGE = "SHIELD_TXC_ROLLBACK_"

// DEFAULT_SHIELD_TXC_TOPIC 默认topic源
const DEFAULT_SHIELD_TXC_TOPIC = "DEFAULT_TXC_XXX"

const DEFAULT_SHIELD_TXC_DATABASE = "DEFAULT_TXC_DATABASE_XXX"

const DEFAULT_SHIELD_TXC_TABLE = "DEFAULT_TXC_TABLE_XXX"

// LOGGER_NAME 日志名称
const LOGGER_NAME = "shieldTxcCommon"

// MAX_COMMIT_RECONSUME_TIMES 事务下游执行提交最大次数
const MAX_COMMIT_RECONSUME_TIMES = 3

// MESSAGE_HAS_EXISTED_INDEX 消息存在索引
const MESSAGE_HAS_EXISTED_INDEX = "message_exists_idx"

// MESSAGE_PRIMARY_KEY_DUPLICATE 消息主键重复
const MESSAGE_PRIMARY_KEY_DUPLICATE = "PRIMARY"
