package constant

const (
	// PRODUCE_INIT 初始化
	PRODUCE_INIT = "PRODUCE_INIT"
	// PRODUCE_PROCESSING 处理中
	PRODUCE_PROCESSING = "PRODUCE_PROCESSING"
	// PRODUCE_PROCESSED 完成
	PRODUCE_PROCESSED = "PRODUCE_PROCESSED"

	// CONSUME_INIT 发布后初始化
	CONSUME_INIT = "CONSUME_INIT"
	// CONSUME_PROCESSING 发布后处理中
	CONSUME_PROCESSING = "CONSUME_PROCESSING"
	// CONSUME_PROCESSED 发布后处理完成
	CONSUME_PROCESSED = "CONSUME_PROCESSED"
	CONSUME_FAILED    = "CONSUME_FAILED"
	// CONSUME_MAX_RECONSUMETIMES 达到最大重试次数
	CONSUME_MAX_RECONSUMETIMES = "CONSUME_MAX_RECONSUMETIMES"
)
